### ISSUE TITLE
Cannot compile on Mac

### ISSUE THREAD

**Issue by Divide-By-0** [nevillegrech/gigahorse-toolchain#33]
Ran
```
brew install boost
brew install --HEAD souffle-lang/souffle/souffle
git clone --recurse-submodules --remote-submodules https://github.com/nevillegrech/gigahorse-toolchain
cd gigahorse-toolchain
cd souffle-addon
make
cd ..
./gigahorse.py examples/long_running.hex
```
and get the error
```  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "./gigahorse.py", line 550, in <module>
    open(v, 'r') # check program exists
FileNotFoundError: [Errno 2] No such file or directory: '.../gigahorse-toolchain/logic/main.dl_compiled'
```

**Comment by iliastsa** [comment]
Unfortunately, our Mac support is really iffy - we are working on improving gigahorse on this front, as it's a more common problem lately.

In order to help add some support, I revamped the Dockerfile. You could try do the following:
1. Build the Docker image: `docker build -t gigahorse .`
2. Set an alias `alias gigahorse=GIGAHORSE_ROOT_ABS_PATH/bin/run_docker`
3. Invoke `gigahorse ARGS`, for example `gigahorse examples/long_running.hex`

It should work, but please let me know if you encounter any issues. Please note that this is experimental and that the home directory is mounted in the container as it's quite likely that people will want to run some client analyses via `gigahorse <HEX> -C <client list>`.

**Comment by Divide-By-0** [comment]
Ah, I think by default I can do those commands without root. However, this fails:
```
gigahorse examples/long_running.hex
zsh: /Users/aayush/Documents/MIT/frontrunner/gigahorse-toolchain/bin/run_docker: bad interpreter: /usr/bin/bash: no such file or directory
```

**Comment by iliastsa** [comment]
We merged PR #35 that should work on M1 Mac - maybe it fixes your issue.

**Comment by Divide-By-0** [comment]
Oh I'm on Intel Mac but I'll give it a shot.
