### ISSUE TITLE
why stop compilation

### ISSUE THREAD

**Issue by taka250** [nevillegrech/gigahorse-toolchain#95]
why stop compilation
failed to compile C++ sources
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/work/gig/gigahorse-toolchain/./gigahorse.py", line 337, in compile_datalog
    assert not(process.returncode), f"Compilation for {spec} failed. Stopping."
AssertionError: Compilation for /root/work/gig/gigahorse-toolchain/clientlib/function_inliner.dl failed. Stopping.
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.

**Comment by sifislag** [comment]
Maybe you ran out of memory?
